{{- if .Values.oracle.enabled }}
{{- if .Values.oracle.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-oracle-pvc
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.oracle.persistence.storageClass }}
  storageClassName: {{ .Values.oracle.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.oracle.persistence.size }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-oracle
  labels:
    app.kubernetes.io/name: oracle-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: oracle-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oracle-db
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 54321:54321 /opt/oracle/oradata && chmod -R 750 /opt/oracle/oradata"]
          volumeMounts:
            - name: oracle-storage
              mountPath: /opt/oracle/oradata
      containers:
        - name: oracle
          image: "{{ .Values.oracle.image.repository }}:{{ .Values.oracle.image.tag }}"
          ports:
            - containerPort: 1521
              name: oracle-port
          env:
            - name: ORACLE_PASSWORD
              value: "{{ .Values.oracle.password }}"
            - name: APP_USER
              value: "indibank"
            - name: APP_USER_PASSWORD
              value: "{{ .Values.oracle.password }}"
          resources:
            {{- toYaml .Values.oracle.resources | nindent 12 }}
          volumeMounts:
            - name: oracle-storage
              mountPath: /opt/oracle/oradata
      volumes:
        - name: oracle-storage
          {{- if .Values.oracle.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-oracle-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-oracle
  labels:
    app.kubernetes.io/name: oracle-db
spec:
  type: ClusterIP
  ports:
    - port: 1521
      targetPort: 1521
      name: oracle-port
  selector:
    app.kubernetes.io/name: oracle-db
{{- end }}
