{{- if and .Values.openshift.route.enabled (eq .Values.targetPlatform "openshift") }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-route
  labels:
    app.kubernetes.io/name: indibank-core
spec:
  host: {{ .Values.openshift.route.host | quote }}
  to:
    kind: Service
    name: {{ .Release.Name }}-core
    weight: 100
  port:
    targetPort: http
  {{- with .Values.openshift.route.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
