-- ============================================================================
-- INDI-BANK CORE TRANSACTION & LEDGER ENGINE - ORACLE 23c SCHEMA SPECIFICATION
-- ============================================================================

-- 1. ACCOUNTS TABLE
-- System of Record for bank accounts, supporting optimistic locking and non-negative balance constraints.
CREATE TABLE ACCOUNTS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACCOUNT_NUMBER VARCHAR2(20) NOT NULL,
    ACCOUNT_HOLDER_NAME VARCHAR2(100) NOT NULL,
    ACCOUNT_TYPE VARCHAR2(30) DEFAULT 'CHECKING' NOT NULL,
    CURRENCY VARCHAR2(3) DEFAULT 'IDR' NOT NULL,
    BALANCE NUMBER(18, 2) DEFAULT 0.00 NOT NULL,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL, -- Optimistic locking
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_ACCOUNTS_NUM UNIQUE (ACCOUNT_NUMBER),
    CONSTRAINT CHK_ACCOUNT_STATUS CHECK (STATUS IN ('ACTIVE', 'DORMANT', 'FROZEN')),
    CONSTRAINT CHK_ACCOUNT_TYPE CHECK (ACCOUNT_TYPE IN ('CHECKING', 'SAVINGS', 'SETTLEMENT_CLEARING')),
    CONSTRAINT CHK_NON_NEGATIVE_BALANCE CHECK (BALANCE >= 0)
);

CREATE INDEX IDX_ACCOUNTS_NUM ON ACCOUNTS(ACCOUNT_NUMBER);

-- 2. TRANSFERS TABLE
-- Stores transfer transactions with unique idempotency keys and state tracking.
CREATE TABLE TRANSFERS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRANSFER_REFERENCE VARCHAR2(40) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(64) NOT NULL,
    SOURCE_ACCOUNT_ID NUMBER NOT NULL,
    DESTINATION_ACCOUNT_ID NUMBER NOT NULL,
    AMOUNT NUMBER(18, 2) NOT NULL,
    CURRENCY VARCHAR2(3) DEFAULT 'IDR' NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    DESCRIPTION VARCHAR2(255),
    JOURNAL_ENTRY_ID NUMBER,
    ERROR_MESSAGE VARCHAR2(500),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UQ_TRANSFERS_REF UNIQUE (TRANSFER_REFERENCE),
    CONSTRAINT UQ_TRANSFERS_IDEMPOTENCY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT FK_TRANSFERS_SRC FOREIGN KEY (SOURCE_ACCOUNT_ID) REFERENCES ACCOUNTS(ID),
    CONSTRAINT FK_TRANSFERS_DST FOREIGN KEY (DESTINATION_ACCOUNT_ID) REFERENCES ACCOUNTS(ID),
    CONSTRAINT CHK_TRANSFER_STATUS CHECK (STATUS IN ('PENDING', 'SETTLED', 'FAILED', 'REJECTED')),
    CONSTRAINT CHK_POSITIVE_AMOUNT CHECK (AMOUNT > 0)
);

CREATE INDEX IDX_TRANSFERS_REF ON TRANSFERS(TRANSFER_REFERENCE);
CREATE INDEX IDX_TRANSFERS_IDEMP ON TRANSFERS(IDEMPOTENCY_KEY);

-- 3. JOURNAL_ENTRIES TABLE
-- Immutable General Ledger double-entry book.
-- Every financial transfer produces exactly two entries (DEBIT source, CREDIT destination).
CREATE TABLE JOURNAL_ENTRIES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRANSFER_ID NUMBER NOT NULL,
    ACCOUNT_ID NUMBER NOT NULL,
    ENTRY_TYPE VARCHAR2(10) NOT NULL, -- 'DEBIT' or 'CREDIT'
    AMOUNT NUMBER(18, 2) NOT NULL,
    BALANCE_AFTER NUMBER(18, 2) NOT NULL,
    DESCRIPTION VARCHAR2(255),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_JOURNAL_TRANSFER FOREIGN KEY (TRANSFER_ID) REFERENCES TRANSFERS(ID),
    CONSTRAINT FK_JOURNAL_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ID),
    CONSTRAINT CHK_ENTRY_TYPE CHECK (ENTRY_TYPE IN ('DEBIT', 'CREDIT')),
    CONSTRAINT CHK_JOURNAL_POSITIVE CHECK (AMOUNT > 0)
);

CREATE INDEX IDX_JOURNAL_ACC ON JOURNAL_ENTRIES(ACCOUNT_ID, CREATED_AT DESC);
CREATE INDEX IDX_JOURNAL_TRX ON JOURNAL_ENTRIES(TRANSFER_ID);

-- 4. OUTBOX_EVENTS TABLE
-- Transactional Outbox Pattern: Ensures 100% reliable publishing to Kafka within Oracle ACID transaction.
CREATE TABLE OUTBOX_EVENTS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EVENT_ID VARCHAR2(64) NOT NULL,
    AGGREGATE_TYPE VARCHAR2(50) NOT NULL,
    AGGREGATE_ID VARCHAR2(64) NOT NULL,
    EVENT_TYPE VARCHAR2(50) NOT NULL,
    PAYLOAD CLOB NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    RETRY_COUNT NUMBER DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PROCESSED_AT TIMESTAMP WITH TIME ZONE,
    CONSTRAINT UQ_OUTBOX_EVENT_ID UNIQUE (EVENT_ID),
    CONSTRAINT CHK_OUTBOX_STATUS CHECK (STATUS IN ('PENDING', 'PUBLISHED', 'FAILED'))
);

CREATE INDEX IDX_OUTBOX_PENDING ON OUTBOX_EVENTS(STATUS, CREATED_AT);

-- 5. INITIAL SEED DATA FOR DEMO & TESTING
INSERT INTO ACCOUNTS (ACCOUNT_NUMBER, ACCOUNT_HOLDER_NAME, ACCOUNT_TYPE, CURRENCY, BALANCE, STATUS)
VALUES ('1001002001', 'Budi Santoso (PT Solusi Digital)', 'CHECKING', 'IDR', 500000000.00, 'ACTIVE');

INSERT INTO ACCOUNTS (ACCOUNT_NUMBER, ACCOUNT_HOLDER_NAME, ACCOUNT_TYPE, CURRENCY, BALANCE, STATUS)
VALUES ('1001002002', 'Siti Rahma (Retail Savings)', 'SAVINGS', 'IDR', 15000000.00, 'ACTIVE');

INSERT INTO ACCOUNTS (ACCOUNT_NUMBER, ACCOUNT_HOLDER_NAME, ACCOUNT_TYPE, CURRENCY, BALANCE, STATUS)
VALUES ('1001002003', 'Indivara Corporate Treasury', 'CHECKING', 'IDR', 1250000000.00, 'ACTIVE');

INSERT INTO ACCOUNTS (ACCOUNT_NUMBER, ACCOUNT_HOLDER_NAME, ACCOUNT_TYPE, CURRENCY, BALANCE, STATUS)
VALUES ('1001002004', 'Ahmad Hidayat (Payroll)', 'SAVINGS', 'IDR', 3200000.00, 'ACTIVE');

INSERT INTO ACCOUNTS (ACCOUNT_NUMBER, ACCOUNT_HOLDER_NAME, ACCOUNT_TYPE, CURRENCY, BALANCE, STATUS)
VALUES ('1001002099', 'National Clearing Settlement GL', 'SETTLEMENT_CLEARING', 'IDR', 9999999999.00, 'ACTIVE');

COMMIT;
