# Overrides for deployment to Azure AKS
targetPlatform: "azure"

app:
  image:
    repository: indibankacr.azurecr.io/indibank-engine
    tag: "latest"

oracle:
  persistence:
    enabled: true
    storageClass: "managed-csi" # Azure Disk CSI driver
    size: 20Gi

ingress:
  enabled: true
  className: "azure/application-gateway"
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: indibank.example.com
      paths:
        - path: /
          pathType: Prefix
